# Generated by Django 2.2.24 on 2022-10-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geneagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source_db2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variantagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(blank=True, max_length=50, null=True)),
                ('source_db', models.CharField(blank=True, max_length=50, null=True)),
                ('drugagmp', models.ForeignKey(blank=True, default='DRUG0', null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp.Drugagmp')),
                ('geneagmp', models.ForeignKey(blank=True, default='GENE0', null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp.Geneagmp')),
            ],
        ),
    ]
