# Generated by Django 2.2.24 on 2022-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugagmp',
            name='drug_bank_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drugagmp',
            name='drug_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drugagmp',
            name='indication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drugagmp',
            name='iupac_name_seq',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drugagmp',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
