# Generated by Django 2.2.24 on 2022-10-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp', '0002_auto_20221018_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantStudyagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_participant', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('geographical_regions', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('p_value', models.CharField(blank=True, max_length=50, null=True)),
                ('variantagmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp.Variantagmp')),
            ],
        ),
    ]
