# Generated by Django 2.2.24 on 2022-10-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp', '0002_auto_20221017_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneagmp',
            name='chromosome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geneagmp',
            name='function',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geneagmp',
            name='gene_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geneagmp',
            name='uniprot_ac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
